-- INSERT QUEENS
INSERT INTO public.queens (id, name, image_url) VALUES
('alyssa-edwards', 'Alyssa Edwards', NULL),
('kitty-scott-claus', 'Kitty Scott-Claus', NULL),
('kween-kong', 'Kween Kong', NULL),
('nehellenia', 'Nehellenia', NULL),
('tessa-testicle', 'Tessa Testicle', NULL),
('vanity-vain', 'Vanity Vain', NULL),
('pythia', 'Pythia', NULL),
('gala-varo', 'Gala Varo', NULL),
('soa-de-muse', 'Soa de Muse', NULL),
('eva-le-queen', 'Eva Le Queen', NULL),
('miranda-lebrao', 'Miranda Lebrão', NULL),
('athena-likis', 'Athena Likis', NULL),
('lazy-susan', 'Lazy Susan', NULL),
('mandy-moobs', 'Mandy Moobs', NULL),
('vybe', 'Vybe', NULL),
('freya-armani', 'Freya Armani', NULL),
('nikita-iman', 'Nikita Iman', NULL),
('max-drag-queen', 'Max Drag Queen', NULL),
('brenda-bressed', 'Brenda Bressed', NULL),
('lucina-innocence', 'Lucina Innocence', NULL),
('karna-ford', 'Karna Ford', NULL),
('olivia-dreams', 'Olivia Dreams', NULL),
('brigiding', 'Brigiding', NULL),
('vinas-deluxe', 'Viñas DeLuxe', NULL),
('arizona-brandy', 'Arizona Brandy', NULL),
('suki-doll', 'Suki Doll', NULL),
('khianna', 'Khianna', NULL),
('yuhua', 'Yuhua', NULL),
('siam-phusri', 'Siam Phusri', NULL),
('bernie', 'Bernie', NULL),
('kitty-space', 'Kitty Space', NULL),
('ivory-glaze', 'Ivory Glaze', NULL),
('sum-ting-wong', 'Sum Ting Wong', NULL),
('madame-yoko', 'Madame Yoko', NULL),
('drag-sethlas', 'Drag Sethlas', NULL),
('samantha-ballentines', 'Samantha Ballentines', NULL),
('hornella-gongora', 'Hornella Góngora', NULL),
('juriji-der-klee', 'Juriji der Klee', NULL),
('pupi-poisson', 'Pupi Poisson', NULL),
('sagittaria', 'Sagittaria', NULL),
('pakita', 'Pakita', NULL),
('onyx-unleashed', 'Onyx Unleashed', NULL),
('pink-chadora', 'Pink Chadora', NULL),
('alexis-mateo', 'Alexis Mateo', NULL),
('barbie-q', 'Barbie Q', NULL),
('desiree-beck', 'DesiRée Beck', NULL),
('elektra-vandergeld', 'Elektra Vandergeld', NULL),
('eva-blunt', 'Eva Blunt', NULL),
('horacio-potasio', 'Horacio Potasio', NULL),
('mariana-stars', 'Mariana Stars', NULL),
('matraka', 'Matraka', NULL),
('miss-abby-omg', 'Miss Abby OMG', NULL),
('regina-voce', 'Regina Voce', NULL),
('xunami-muse', 'Xunami Muse', NULL),
('azemylia', 'Azemylia', NULL),
('creatine-price', 'Creatine Price', NULL),
('daisy-superbitch', 'Daisy Superbitch', NULL),
('fluffy-bidule', 'Fluffy Bidule', NULL),
('holly-white', 'Holly White', NULL),
('la-harpie', 'La Harpie', NULL),
('lana-cotta', 'Lana Cotta', NULL),
('malawitte', 'Malawitte', NULL),
('margarette', 'Margarette', NULL),
('sublyme', 'Sublyme', NULL),
('art-simone', 'Art Simone', NULL),
('coco-jumbo', 'Coco Jumbo', NULL),
('estrella-xtravaganza', 'Estrella Xtravaganza', NULL),
('flor', 'Flor', NULL),
('lala-ri', 'LaLa Ri', NULL),
('m1ss-jade-so', 'M1ss Jade So', NULL),
('michael-marouli', 'Michael Marouli', NULL),
('nicole-paige-brooks', 'Nicole Paige Brooks', NULL),
('raven', 'Raven', NULL),
('mami-watta', 'Mami Watta', NULL),
('elips', 'Elips', NULL),
('misty-phoenix', 'Misty Phoenix', NULL),
('piche', 'Piche', NULL),
('moon', 'Moon', NULL),
('kam-hugh', 'Kam Hugh', NULL),
('la-big-bertha', 'La Big Bertha', NULL),
('punani', 'Punani', NULL),
('magnetica', 'Magnetica', NULL)
ON CONFLICT (id) DO NOTHING;

-- INSERT SEASON QUEENS
INSERT INTO public.season_queens (season_id, queen_id, placement) VALUES
('global-all-stars-s1', 'alyssa-edwards', 'Winner'),
('global-all-stars-s1', 'kitty-scott-claus', 'Runner-up'),
('global-all-stars-s1', 'kween-kong', 'Runner-up'),
('global-all-stars-s1', 'nehellenia', 'Runner-up'),
('global-all-stars-s1', 'tessa-testicle', '5th Place'),
('global-all-stars-s1', 'vanity-vain', '6th Place'),
('global-all-stars-s1', 'pythia', '7th Place'),
('global-all-stars-s1', 'gala-varo', '8th Place'),
('global-all-stars-s1', 'soa-de-muse', '9th Place'),
('global-all-stars-s1', 'eva-le-queen', '10th Place'),
('global-all-stars-s1', 'miranda-lebrao', '11th Place'),
('global-all-stars-s1', 'athena-likis', '12th Place'),
('down-under-s4', 'lazy-susan', 'Winner'),
('down-under-s4', 'mandy-moobs', 'Runner-up'),
('down-under-s4', 'vybe', 'Runner-up'),
('down-under-s4', 'freya-armani', '4th Place'),
('down-under-s4', 'nikita-iman', '5th Place'),
('down-under-s4', 'max-drag-queen', '6th Place'),
('down-under-s4', 'brenda-bressed', '7th Place'),
('down-under-s4', 'lucina-innocence', '8th Place'),
('down-under-s4', 'karna-ford', '9th Place'),
('down-under-s4', 'olivia-dreams', '10th Place'),
('philippines-slaysian-s1', 'brigiding', 'Winner'),
('philippines-slaysian-s1', 'vinas-deluxe', 'Runner-up'),
('philippines-slaysian-s1', 'arizona-brandy', '3rd/4th Place'),
('philippines-slaysian-s1', 'suki-doll', '3rd/4th Place'),
('philippines-slaysian-s1', 'khianna', '5th Place'),
('philippines-slaysian-s1', 'yuhua', '6th Place'),
('philippines-slaysian-s1', 'siam-phusri', '7th Place'),
('philippines-slaysian-s1', 'bernie', '8th Place'),
('philippines-slaysian-s1', 'kitty-space', '9th Place'),
('philippines-slaysian-s1', 'ivory-glaze', '10th Place'),
('philippines-slaysian-s1', 'sum-ting-wong', '11th Place'),
('philippines-slaysian-s1', 'madame-yoko', '12th Place'),
('espana-all-stars-s1', 'drag-sethlas', 'Winner'),
('espana-all-stars-s1', 'samantha-ballentines', 'Runner-up'),
('espana-all-stars-s1', 'hornella-gongora', '3rd/4th'),
('espana-all-stars-s1', 'juriji-der-klee', '3rd/4th'),
('espana-all-stars-s1', 'pupi-poisson', '5th'),
('espana-all-stars-s1', 'sagittaria', '6th'),
('espana-all-stars-s1', 'pakita', '7th'),
('espana-all-stars-s1', 'onyx-unleashed', '8th'),
('espana-all-stars-s1', 'pink-chadora', '9th'),
('mexico-latina-royale-s1', 'alexis-mateo', 'TBA'),
('mexico-latina-royale-s1', 'barbie-q', 'TBA'),
('mexico-latina-royale-s1', 'desiree-beck', 'TBA'),
('mexico-latina-royale-s1', 'elektra-vandergeld', 'TBA'),
('mexico-latina-royale-s1', 'eva-blunt', 'TBA'),
('mexico-latina-royale-s1', 'horacio-potasio', 'TBA'),
('mexico-latina-royale-s1', 'mariana-stars', 'TBA'),
('mexico-latina-royale-s1', 'matraka', 'TBA'),
('mexico-latina-royale-s1', 'miss-abby-omg', 'TBA'),
('mexico-latina-royale-s1', 'regina-voce', 'TBA'),
('mexico-latina-royale-s1', 'xunami-muse', 'TBA'),
('france-s4', 'azemylia', 'Contestant'),
('france-s4', 'creatine-price', '10th Place'),
('france-s4', 'daisy-superbitch', 'Contestant'),
('france-s4', 'fluffy-bidule', 'Contestant'),
('france-s4', 'holly-white', '7th Place'),
('france-s4', 'la-harpie', 'Contestant'),
('france-s4', 'lana-cotta', 'Contestant'),
('france-s4', 'malawitte', '9th Place'),
('france-s4', 'margarette', '8th Place'),
('france-s4', 'sublyme', 'Contestant'),
('down-under-vs-tw-s1', 'art-simone', 'TBA'),
('down-under-vs-tw-s1', 'coco-jumbo', 'TBA'),
('down-under-vs-tw-s1', 'estrella-xtravaganza', 'TBA'),
('down-under-vs-tw-s1', 'flor', 'TBA'),
('down-under-vs-tw-s1', 'lala-ri', 'TBA'),
('down-under-vs-tw-s1', 'm1ss-jade-so', 'TBA'),
('down-under-vs-tw-s1', 'michael-marouli', 'TBA'),
('down-under-vs-tw-s1', 'nicole-paige-brooks', '10th Place'),
('down-under-vs-tw-s1', 'nikita-iman', 'TBA'),
('down-under-vs-tw-s1', 'raven', 'Mole'),
('down-under-vs-tw-s1', 'vybe', 'TBA'),
('france-all-stars-s1', 'mami-watta', 'Winner'),
('france-all-stars-s1', 'elips', 'Runner-up'),
('france-all-stars-s1', 'misty-phoenix', '3rd/4th Place'),
('france-all-stars-s1', 'piche', '3rd/4th Place'),
('france-all-stars-s1', 'moon', '5th Place'),
('france-all-stars-s1', 'kam-hugh', '6th Place'),
('france-all-stars-s1', 'la-big-bertha', '7th Place'),
('france-all-stars-s1', 'punani', '8th Place'),
('france-all-stars-s1', 'soa-de-muse', '9th Place'),
('france-all-stars-s1', 'magnetica', '10th Place')
ON CONFLICT ON CONSTRAINT season_queens_pkey DO NOTHING;

-- INSERT EPISODES
INSERT INTO public.episodes (id, season_id, episode_number, title, air_date) VALUES
('global-all-stars-s1-e1', 'global-all-stars-s1', 1, 'Global Talent Extravaganza', 'August 16, 2024'),
('global-all-stars-s1-e2', 'global-all-stars-s1', 2, 'Global Talent Extravaganza: Part 2', 'August 16, 2024'),
('global-all-stars-s1-e3', 'global-all-stars-s1', 3, 'International Queen Of Mystery Ball', 'August 23, 2024'),
('global-all-stars-s1-e4', 'global-all-stars-s1', 4, 'Everybody Say Love Girl Groups', 'August 30, 2024'),
('global-all-stars-s1-e5', 'global-all-stars-s1', 5, 'Boobie: The Shequels', 'September 6, 2024'),
('global-all-stars-s1-e6', 'global-all-stars-s1', 6, 'It''s 5 O''Clock Somewhere', 'September 13, 2024'),
('global-all-stars-s1-e7', 'global-all-stars-s1', 7, 'Snatch Game Of Love', 'September 20, 2024'),
('global-all-stars-s1-e8', 'global-all-stars-s1', 8, 'Mmm... A Rich International Roast', 'September 27, 2024'),
('global-all-stars-s1-e9', 'global-all-stars-s1', 9, 'Re-United Nations Make-Overs', 'October 4, 2024'),
('global-all-stars-s1-e10', 'global-all-stars-s1', 10, 'There''s No Place Like Home', 'October 11, 2024'),
('global-all-stars-s1-e11', 'global-all-stars-s1', 11, 'Global Lip-Sync Lalaparuza', 'October 18, 2024'),
('global-all-stars-s1-e12', 'global-all-stars-s1', 12, 'Dance Like The World Is Watching', 'October 25, 2024'),
('down-under-s4-e1', 'down-under-s4', 1, 'Doubling Down', 'November 1, 2024'),
('down-under-s4-e2', 'down-under-s4', 2, 'Mr. Right or Mr. Right Now?', 'November 8, 2024'),
('down-under-s4-e3', 'down-under-s4', 3, 'Snatch Game', 'November 15, 2024'),
('down-under-s4-e4', 'down-under-s4', 4, 'Fierce Fabulous Fashion', 'November 22, 2024'),
('down-under-s4-e5', 'down-under-s4', 5, 'Booked and Beautiful', 'November 29, 2024'),
('down-under-s4-e6', 'down-under-s4', 6, 'Platy-Pussies On Fire', 'December 6, 2024'),
('down-under-s4-e7', 'down-under-s4', 7, 'The Rhys Roast', 'December 13, 2024'),
('down-under-s4-e8', 'down-under-s4', 8, 'Grand Finale', 'December 20, 2024'),
('philippines-slaysian-s1-e1', 'philippines-slaysian-s1', 1, 'Miss Shutacca: Slaysian Edition', 'August 13, 2025'),
('philippines-slaysian-s1-e2', 'philippines-slaysian-s1', 2, 'Asian Eyyy!', 'August 20, 2025'),
('philippines-slaysian-s1-e3', 'philippines-slaysian-s1', 3, 'Holy Cacao!', 'August 27, 2025'),
('philippines-slaysian-s1-e4', 'philippines-slaysian-s1', 4, 'Crazy Bitch Slaysians: The Musical', 'September 3, 2025'),
('philippines-slaysian-s1-e5', 'philippines-slaysian-s1', 5, 'Homecoming Queens', 'September 10, 2025'),
('philippines-slaysian-s1-e6', 'philippines-slaysian-s1', 6, 'Snatch Election', 'September 17, 2025'),
('philippines-slaysian-s1-e7', 'philippines-slaysian-s1', 7, 'Lip Sync Lalaparuza Smackdown', 'September 24, 2025'),
('philippines-slaysian-s1-e8', 'philippines-slaysian-s1', 8, 'DragCon Slaysia!', 'October 1, 2025'),
('philippines-slaysian-s1-e9', 'philippines-slaysian-s1', 9, 'High Time', 'October 8, 2025'),
('philippines-slaysian-s1-e10', 'philippines-slaysian-s1', 10, 'Slaysian Grand T.I.T.E.! (Totally Impressive Talent Extravaganza!)', 'October 15, 2025'),
('espana-all-stars-s1-e1', 'espana-all-stars-s1', 1, 'Supremme Eleganza Olé Stars Extravaganza', 'February 4, 2024'),
('espana-all-stars-s1-e2', 'espana-all-stars-s1', 2, 'Snatch Game', 'February 11, 2024'),
('espana-all-stars-s1-e3', 'espana-all-stars-s1', 3, 'The Ball: Heaven, Hell, and Capital Sins', 'February 18, 2024'),
('espana-all-stars-s1-e4', 'espana-all-stars-s1', 4, 'Girl Bands Battle', 'February 25, 2024'),
('espana-all-stars-s1-e5', 'espana-all-stars-s1', 5, 'The Hairdresser''s Salon', 'March 3, 2024'),
('espana-all-stars-s1-e6', 'espana-all-stars-s1', 6, 'The Reunion', 'March 10, 2024'),
('espana-all-stars-s1-e7', 'espana-all-stars-s1', 7, 'Grand Finale', 'March 17, 2024'),
('mexico-latina-royale-s1-e1', 'mexico-latina-royale-s1', 1, 'United By a Language, Separated By a Crown', 'July 30, 2026'),
('france-s4-e1', 'france-s4', 1, 'Drag Academy', 'July 8, 2026'),
('france-s4-e2', 'france-s4', 2, 'La Boulangerie Est Ouverte', 'July 16, 2026'),
('france-s4-e3', 'france-s4', 3, 'Drag Vinci Code, The Musidrag', 'July 23, 2026'),
('france-s4-e4', 'france-s4', 4, 'Le Grand Snatch Game', 'July 30, 2026'),
('france-s4-e5', 'france-s4', 5, 'Pop Couture', 'August 6, 2026'),
('down-under-vs-tw-s1-e1', 'down-under-vs-tw-s1', 1, 'Look Who''s Back In The House!', 'July 24, 2026'),
('down-under-vs-tw-s1-e2', 'down-under-vs-tw-s1', 2, 'Better The Diva You Know', 'July 31, 2026'),
('down-under-vs-tw-s1-e3', 'down-under-vs-tw-s1', 3, 'TBA', 'August 7, 2026'),
('down-under-vs-tw-s1-e4', 'down-under-vs-tw-s1', 4, 'TBA', 'August 14, 2026'),
('down-under-vs-tw-s1-e5', 'down-under-vs-tw-s1', 5, 'TBA', 'August 21, 2026'),
('down-under-vs-tw-s1-e6', 'down-under-vs-tw-s1', 6, 'TBA', 'August 28, 2026'),
('down-under-vs-tw-s1-e7', 'down-under-vs-tw-s1', 7, 'TBA', 'September 4, 2026'),
('down-under-vs-tw-s1-e8', 'down-under-vs-tw-s1', 8, 'TBA', 'September 11, 2026'),
('france-all-stars-s1-e1', 'france-all-stars-s1', 1, 'Abracada-Drag', 'July 10, 2025'),
('france-all-stars-s1-e2', 'france-all-stars-s1', 2, 'Super Ball', 'July 17, 2025'),
('france-all-stars-s1-e3', 'france-all-stars-s1', 3, 'Golden Snatch Game', 'July 24, 2025'),
('france-all-stars-s1-e4', 'france-all-stars-s1', 4, 'Superstars', 'July 31, 2025'),
('france-all-stars-s1-e5', 'france-all-stars-s1', 5, 'VIP Makeover', 'August 7, 2025'),
('france-all-stars-s1-e6', 'france-all-stars-s1', 6, 'Queenovision', 'August 14, 2025'),
('france-all-stars-s1-e7', 'france-all-stars-s1', 7, 'The Nicky d''Or', 'August 21, 2025'),
('france-all-stars-s1-e8', 'france-all-stars-s1', 8, 'The Finale', 'August 28, 2025')
ON CONFLICT (id) DO NOTHING;

