INSERT INTO franchises (id, name, country) VALUES 
('us-all-stars', 'RuPaul''s Drag Race All Stars', 'US'),
('us-all-stars-untucked', 'RuPaul''s Drag Race All Stars Untucked!', 'US'),
('can-all-stars', 'Canada''s Drag Race: Canada vs. The World', 'Canada'),
('us-regular', 'RuPaul''s Drag Race', 'US'),
('us-untucked', 'RuPaul''s Drag Race Untucked!', 'US'),
('can-regular', 'Canada''s Drag Race', 'Canada'),
('belgique', 'Drag Race Belgique', 'Belgium'),
('brasil', 'Drag Race Brasil', 'Brazil'),
('down-under', 'RuPaul''s Drag Race Down Under', 'Australia'),
('down-under-vs-tw', 'RuPaul''s Drag Race Down Under vs. The World', 'Australia'),
('espana', 'Drag Race España', 'Spain'),
('espana-all-stars', 'Drag Race España All Stars', 'Spain'),
('france', 'Drag Race France', 'France'),
('france-all-stars', 'Drag Race France All Stars', 'France'),
('germany', 'Drag Race Germany', 'Germany'),
('holland', 'Drag Race Holland', 'Netherlands'),
('italia', 'Drag Race Italia', 'Italy'),
('mexico', 'Drag Race México', 'Mexico'),
('mexico-el-recuento', 'Drag Race México: El Recuento', 'Mexico'),
('mexico-latina-royale', 'Drag Race México: Latina Royale', 'Mexico'),
('philippines', 'Drag Race Philippines', 'Philippines'),
('philippines-slaysian', 'Drag Race Philippines: Slaysian Royale', 'Philippines'),
('philippines-untucked', 'Drag Race Philippines: Untucked!', 'Philippines'),
('sverige', 'Drag Race Sverige', 'Sweden'),
('thailand', 'Drag Race Thailand', 'Thailand'),
('global-all-stars', 'RuPaul''s Drag Race Global All Stars', 'Global'),
('uk-regular', 'RuPaul''s Drag Race UK', 'UK'),
('uk-vs-tw', 'RuPaul''s Drag Race UK vs. The World', 'UK'),
('secret-celebrity', 'RuPaul''s Secret Celebrity Drag Race', 'US'),
('ruvealed-us', 'RuVealed: RuPaul''s Drag Race', 'US')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
