-- O ROBÔ DEFINITIVO - FANDOM API SCRAPING

-- 1. Inserindo Queens com Fotos
INSERT INTO queens (id, name, image_url) VALUES
('design', 'Design', ''),
('priyanka', 'Priyanka', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/0/0d/PriyankaPromo.jpg'),
('rita-baga', 'Rita Baga', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/d/d2/RitaPromo.jpg'),
('scarlett-bobo', 'Scarlett BoBo', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/d/dc/ScarlettBoBoPromo.jpg'),
('jimbo', 'Jimbo', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/e/e5/JimboPromo.jpg'),
('lemon', 'Lemon', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/f/f2/LemonPromo.jpg'),
('ilona-verley', 'Ilona Verley', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/e/eb/IlonaPromo.jpg'),
('boa', 'BOA', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/7/72/BoaPromo.jpg'),
('kiara', 'Kiara', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/c/c1/KiaraPromo.jpg'),
('tynomi-banks', 'Tynomi Banks', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/d/d8/TynomiPromo.jpg'),
('anastarzia-anaquway', 'Anastarzia Anaquway', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/1/10/AnastarziaPromo.jpg'),
('kyne', 'Kyne', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/6/6c/KynePromo.jpg'),
('juice-boxx', 'Juice Boxx', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/b/b6/JuicePromo.jpg'),
('bebe-zahara-benet', 'Bebe Zahara Benet', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/4/40/BeBeZaharaBenetS1CastMug.png'),
('nina-flowers', 'Nina Flowers', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/6/6f/NinaFlowersS1CastMug.png'),
('rebecca-glasscock', 'Rebecca Glasscock', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/a/ae/RebeccaGlasscockS1CastMug.png'),
('shannel', 'Shannel', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/a/a7/ShannelS1CastMug.png'),
('ongina', 'Ongina', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/c/c3/OnginaS1CastMug.png'),
('jade', 'Jade', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/5/57/JadeSotomayorS1CastMug.png'),
('akashia', 'Akashia', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/a/a4/AkashiaS1CastMug.png'),
('tammie-brown', 'Tammie Brown', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/9/96/TammieBrownS1CastMug.png'),
('victoria-parker', 'Victoria Parker', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/5/5c/VictoriaParkerS1CastMug.png'),
('tyra-sanchez', 'Tyra Sanchez', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/d/d5/TyraSanchezS2CastMug.png'),
('raven', 'Raven', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/6/68/RavenS2CastMug.png'),
('jujubee', 'Jujubee', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/0/06/JujubeeS2CastMug.png'),
('tatianna', 'Tatianna', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/6/63/TatiannaS2CastMug.png'),
('pandora-boxx', 'Pandora Boxx', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/9/98/PandoraBoxxS2CastMug.png'),
('jessica-wild', 'Jessica Wild', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/9/98/JessicaWildS2CastMug.png'),
('sahara-davenport', 'Sahara Davenport', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/b/b1/SaharaDavenportS2CastMug.png'),
('morgan-mcmichaels', 'Morgan McMichaels', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/7/76/MorganMcMichaelsS2CastMug.png'),
('sonique', 'Sonique', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/9/97/SoniqueS2CastMug.png'),
('mystique-summers-madison', 'Mystique Summers Madison', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/d/d6/MystiqueSummersMadisonS2CastMug.png'),
('nicole-paige-brooks', 'Nicole Paige Brooks', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/c/c5/NicolePaigeBrooksS2CastMug.png'),
('shangela-laquifa-wadley', 'Shangela Laquifa Wadley', 'https://static.wikia.nocookie.net/logosrupaulsdragrace/images/7/7f/ShangelaS2CastMug.png')
ON CONFLICT (id) DO UPDATE SET image_url = EXCLUDED.image_url;

-- 2. Vinculando Queens às Temporadas
INSERT INTO season_queens (season_id, queen_id) VALUES
('can-regular-s1', 'design'),
('can-regular-s1', 'priyanka'),
('can-regular-s1', 'rita-baga'),
('can-regular-s1', 'scarlett-bobo'),
('can-regular-s1', 'jimbo'),
('can-regular-s1', 'lemon'),
('can-regular-s1', 'ilona-verley'),
('can-regular-s1', 'boa'),
('can-regular-s1', 'kiara'),
('can-regular-s1', 'tynomi-banks'),
('can-regular-s1', 'anastarzia-anaquway'),
('can-regular-s1', 'kyne'),
('can-regular-s1', 'juice-boxx'),
('us-regular-s1', 'design'),
('us-regular-s1', 'bebe-zahara-benet'),
('us-regular-s1', 'nina-flowers'),
('us-regular-s1', 'rebecca-glasscock'),
('us-regular-s1', 'shannel'),
('us-regular-s1', 'ongina'),
('us-regular-s1', 'jade'),
('us-regular-s1', 'akashia'),
('us-regular-s1', 'tammie-brown'),
('us-regular-s1', 'victoria-parker'),
('us-regular-s2', 'design'),
('us-regular-s2', 'tyra-sanchez'),
('us-regular-s2', 'raven'),
('us-regular-s2', 'jujubee'),
('us-regular-s2', 'tatianna'),
('us-regular-s2', 'pandora-boxx'),
('us-regular-s2', 'jessica-wild'),
('us-regular-s2', 'sahara-davenport'),
('us-regular-s2', 'morgan-mcmichaels'),
('us-regular-s2', 'sonique'),
('us-regular-s2', 'mystique-summers-madison'),
('us-regular-s2', 'nicole-paige-brooks'),
('us-regular-s2', 'shangela-laquifa-wadley')
ON CONFLICT DO NOTHING;

-- 3. Cadastrando Resultados dos Episódios
INSERT INTO episode_results (episode_id, queen_id, status) VALUES
('us-all-stars-s8-e15', 'jimbo', 'winner'),
('us-all-stars-s8-e3', 'kandy-muse', 'runner_up'),
('us-all-stars-s8-e12', 'alexis-michelle', 'eliminated'),
('us-all-stars-s8-e11', 'lala-ri', 'eliminated'),
('us-all-stars-s8-e15', 'lala-ri', 'winner'),
('us-all-stars-s8-e10', 'kahanna-montrese', 'eliminated'),
('us-all-stars-s8-e9', 'jaymes-mansfield', 'eliminated'),
('us-all-stars-s8-e7', 'darienne-lake', 'eliminated'),
('us-all-stars-s8-e6', 'mrs-kasha-davis', 'eliminated'),
('us-all-stars-s8-e5', 'naysha-lopez', 'eliminated'),
('us-all-stars-s8-e4', 'monica-beverly-hillz', 'eliminated')
ON CONFLICT DO NOTHING;

